#!/bin/bash
# Damla Okul — ilk kurulum (git clone sonrası, Windows Git Bash / macOS / Linux).
# Bağımlılıkları kurar, font WOFF2 subset üretir, build doğrular.
# Geliştirme hook'ları (görsel kontrol, webp) yalnızca start.sh içindedir.

set -uo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

echo "=== Damla Okul — İlk Kurulum ==="
echo "Kök: $ROOT"
echo ""

fail() {
  echo "Hata: $1" >&2
  exit 1
}

# --- Ön koşullar ---
if ! command -v ruby >/dev/null 2>&1; then
  fail "Ruby bulunamadı. Windows: https://rubyinstaller.org — Ruby 3.x + Devkit kurun, Git Bash'i yeniden açın."
fi

echo "Ruby: $(ruby -version 2>&1 | head -1)"

if ! command -v bundle >/dev/null 2>&1; then
  echo "Bundler kuruluyor..."
  gem install bundler || fail "Bundler kurulamadı."
fi

echo "Bundler: $(bundle -v)"
echo ""

# --- Ruby gem bağımlılıkları ---
echo ">>> bundle install"
bundle install || fail "bundle install başarısız."
echo ""

# --- Python fonttools (WOFF2 subset için) ---
echo ">>> Python fonttools"
PYTHON=""
if command -v python3 >/dev/null 2>&1; then
  PYTHON="python3"
elif command -v python >/dev/null 2>&1; then
  PYTHON="python"
fi

if [ -n "$PYTHON" ]; then
  "$PYTHON" -m pip install fonttools brotli -q 2>/dev/null || \
    echo "Uyarı: fonttools kurulamadı; pip install fonttools brotli ile manuel deneyin."
else
  echo "Uyarı: Python bulunamadı; WOFF2 dönüşümü atlanacak."
fi
echo ""

# --- Font WOFF2 subset (eksik veya eski dosyalar) ---
if [ -f "scripts/subset_font.sh" ]; then
  echo ">>> WOFF2 font dönüşümü (subset_font.sh — mevcut woff2 güncel ise atlanır)"
  sh scripts/subset_font.sh || echo "Uyarı: subset_font.sh tamamlanamadı."
  echo ""
fi

if [ -f "scripts/check_fonts.sh" ]; then
  echo ">>> Font boyut kontrolü"
  sh scripts/check_fonts.sh
  echo ""
fi

# --- Görsel araçları (WebP / ImageMagick) ---
if [ -f "scripts/install_image_tools.sh" ]; then
  sh scripts/install_image_tools.sh
  echo ""
fi

# --- Jekyll data dosyaları ---
if [ ! -f "_data/webp_manifest.yml" ]; then
  echo ">>> _data/webp_manifest.yml oluşturuluyor"
  mkdir -p "_data"
  cat > "_data/webp_manifest.yml" <<'EOF'
# Auto-generated by scripts/generate_webp.sh — do not edit manually
assets: []
EOF
  echo ""
fi

# --- Kurulum doğrulama ---
echo ">>> Jekyll build (kurulum doğrulama)"
bundle exec jekyll build || fail "jekyll build başarısız — kurulumu kontrol edin."
echo ""

echo "=== Kurulum tamamlandı ==="
echo "Geliştirme sunucusu: sh start.sh"
echo "Tarayıcı: http://localhost:4000"
echo ""
