#!/bin/bash
# Eksik .webp dosyalarını jpg/png kaynaklarından üretir; _data/webp_manifest.yml yazar.

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# shellcheck source=refresh_image_paths.sh
. "$ROOT/scripts/refresh_image_paths.sh"
refresh_image_tool_paths

SCAN_DIRS=(
  "assets/images/ean"
  "assets/images/slides"
)
SCAN_ROOT_DIRS=(
  "assets/images"
)
MANIFEST="_data/webp_manifest.yml"
QUALITY=82
GENERATED=0
SKIPPED=0
FAILED=0
TOOL=""

detect_tool() {
  if command -v cwebp >/dev/null 2>&1; then
    TOOL="cwebp"
    return 0
  fi
  if command -v magick >/dev/null 2>&1; then
    TOOL="magick"
    return 0
  fi
  if command -v convert >/dev/null 2>&1; then
    # Windows ships a different `convert` — only use ImageMagick's binary
    if convert -version 2>/dev/null | grep -qi 'ImageMagick'; then
      TOOL="convert"
      return 0
    fi
  fi
  return 1
}

to_webp_path() {
  local src="$1"
  local base="${src%.*}"
  echo "${base}.webp"
}

needs_regenerate() {
  local src="$1"
  local dst="$2"
  if [ ! -f "$dst" ]; then
    return 0
  fi
  if [ "$src" -nt "$dst" ]; then
    return 0
  fi
  return 1
}

convert_to_webp() {
  local src="$1"
  local dst="$2"

  case "$TOOL" in
    cwebp)
      cwebp -q "$QUALITY" "$src" -o "$dst" >/dev/null 2>&1
      ;;
    magick)
      magick "$src" -quality "$QUALITY" "$dst" >/dev/null 2>&1
      ;;
    convert)
      convert "$src" -quality "$QUALITY" "$dst" >/dev/null 2>&1
      ;;
    *)
      return 1
      ;;
  esac
}

write_manifest() {
  mkdir -p "_data"
  {
    echo "# Auto-generated by scripts/generate_webp.sh — do not edit manually"
    echo "assets:"
    for dir in "${SCAN_DIRS[@]}"; do
      if [ ! -d "$dir" ]; then
        continue
      fi
      while IFS= read -r -d '' webp; do
        webp="${webp//\\/\/}"
        echo "  - ${webp}"
      done < <(find "$dir" -type f -iname '*.webp' -print0 | sort -z)
    done
    for dir in "${SCAN_ROOT_DIRS[@]}"; do
      if [ ! -d "$dir" ]; then
        continue
      fi
      while IFS= read -r -d '' webp; do
        webp="${webp//\\/\/}"
        echo "  - ${webp}"
      done < <(find "$dir" -maxdepth 1 -type f -iname '*.webp' -print0 | sort -z)
    done
  } > "$MANIFEST"
}

echo "WebP üretimi (scripts/generate_webp.sh)..."

if ! detect_tool; then
  echo "Uyarı: cwebp veya ImageMagick bulunamadı; .webp üretimi atlanıyor (jpg/png ile devam)."
  write_manifest
  exit 0
fi

echo "Kullanılan araç: $TOOL"

for dir in "${SCAN_DIRS[@]}"; do
  if [ ! -d "$dir" ]; then
    continue
  fi

  while IFS= read -r -d '' src; do
    src="${src//\\/\/}"
    dst="$(to_webp_path "$src")"

    if ! needs_regenerate "$src" "$dst"; then
      SKIPPED=$((SKIPPED + 1))
      continue
    fi

    if convert_to_webp "$src" "$dst"; then
      GENERATED=$((GENERATED + 1))
      echo "  + $dst"
    else
      FAILED=$((FAILED + 1))
      echo "  ! Başarısız: $src" >&2
    fi
  done < <(find "$dir" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) -print0)
done

for dir in "${SCAN_ROOT_DIRS[@]}"; do
  if [ ! -d "$dir" ]; then
    continue
  fi

  while IFS= read -r -d '' src; do
    src="${src//\\/\/}"
    dst="$(to_webp_path "$src")"

    if ! needs_regenerate "$src" "$dst"; then
      SKIPPED=$((SKIPPED + 1))
      continue
    fi

    if convert_to_webp "$src" "$dst"; then
      GENERATED=$((GENERATED + 1))
      echo "  + $dst"
    else
      FAILED=$((FAILED + 1))
      echo "  ! Başarısız: $src" >&2
    fi
  done < <(find "$dir" -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) -print0)
done

write_manifest

echo "WebP: $GENERATED üretildi, $SKIPPED güncel, $FAILED hata. Manifest: $MANIFEST"
